# Generated by Django 3.1.5 on 2021-02-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='details_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_text',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=64, null=True, verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.CharField(max_length=64, null=True, verbose_name='Сорт'),
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(max_length=1000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категорія', to='App_shop.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(upload_to='Product', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
    ]
